version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    #    networks:
    #      - monitoring-network
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 8080:9090

#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    #    networks:
#    #      - monitoring-network
#    ports:
#      - 3000:3000
#    volumes:
#      - ./grafana/provisioning:/etc/grafana/provisioning
#      - ./grafana/dashboards:/var/lib/grafana/dashboards
#    depends_on:
#      - prometheus

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    #    networks:
    #      - monitoring-network
    ports:
      - 9100:9100
    depends_on:
      - prometheus

  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/matviichuk_andrii_db
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "12072001"
    ports:
      - 9090:9090

  db:
    image: mysql
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=12072001
      - MYSQL_DATABASE=matviichuk_andrii_db
      - MYSQL_USER=Matviichuk Andrii
      - MYSQL_PASSWORD=12072001
    ports:
      - 3307:3306

